<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_PromoCountdown
 */
use Magento\Framework\App\Action\Action;

?>
<?php /** @var \Ecommage\CatalogPromoCountdown\Block\Widgets\Countdown $block */ ?>
<?php
$bgColor = $block->getData('backgroundColor');
$bgColorLight = $block->luminance($bgColor, 55);
$status = $block->getStatusDisplay();
$widgetId = "amasty-promo-countdown-" . $block->getPostfix();
?>
<div id="<?= $widgetId ?>" <?= /* @noEscape */ (!$status) ? 'class="no-countdown"' : ''?> data-bind="scope: '<?= $widgetId ?>'">
    <style type="text/css">
        <?php if ($block->getData('design') === \Amasty\PromoCountdown\Model\Config\Design::PROGRESS): ?>
        #<?= $widgetId ?> .amcountdown-block-wrapper.-progress .amcountdown-progress::-webkit-progress-value {
            background: linear-gradient(90deg, <?= $bgColorLight ?>  0%, <?= $bgColor ?> 100%);
        }
        #<?= $widgetId ?> .amcountdown-block-wrapper.-progress .amcountdown-progress::-moz-progress-bar {
                              background: linear-gradient(90deg, <?= $bgColorLight ?>  0%, <?= $bgColor ?> 100%);
                          }
        #<?= $widgetId ?> .amcountdown-block-wrapper.-progress .amcountdown-progress::-ms-fill {
                              background: linear-gradient(90deg, <?= $bgColorLight ?>  0%, <?= $bgColor ?> 100%);
                          }
        #<?= $widgetId ?> .amcountdown-block-wrapper.-progress .amcountdown-progressbar:before {
                              background: <?= $bgColorLight ?>;
                          }
        #<?= $widgetId ?> .amcountdown-block-wrapper.-progress .amcountdown-pointer {
                              background: <?= $bgColor ?>;
                          }
        <?php elseif ($block->getData('design') === \Amasty\PromoCountdown\Model\Config\Design::ROUND): ?>
        .amcountdown-block-wrapper.-round .amcountdown-pointer.-static {
            fill: <?= $bgColorLight ?>;
        }
        .amcountdown-block-wrapper.-round .amcountdown-pointer {
            fill: <?= $bgColor ?>;
        }
        <?php endif; ?>
    </style>

    <?php if ($block->getRequest()->getFullActionName() == 'catalog_product_view'): ?>
        <style>
            .product-info-main .widget-product-tagline {
                display: block;
            }
            @media (min-width:662px) {
                .product-info-main .product-add-form {
                    float: left;
                }
            }
            [id^="amasty-promo-countdown-"] {
                display: inline-block;
            }
            [id^="amasty-promo-countdown-"] #timer-default {
                max-width: unset;
                padding-top: 0;
                padding-left: 0;
                padding-bottom: 40px;
            }
            .product-info-main .product.attribute.ox-expand.overview {
                display: inline-block;
            }
            [id^="amasty-promo-countdown-"] #timer-default .amcountdown-text {
                margin-bottom: 0;
            }
        </style>
    <?php endif; ?>


    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "amasty-promo-countdown-<?= $block->getPostfix() ?>": {
                            "component": "Amasty_PromoCountdown/js/countdown",
                            "widgetId": "<?= $widgetId ?>",
                            "serviceUrl": "<?= $block->getServiceUrl() ?>",
                            "targetTime": "<?= $block->getTargetTime() ?>",
                            "startTime": "<?= $block->getStartTime() ?>",
                            "link": "<?= $block->getData('link') ?>",
                            "backgroundColor": "<?= $bgColor ?>",
                            "backgroundColorLight": "<?= $bgColorLight ?>",
                            "textBefore": <?= json_encode($block->getData('text_before')) ?>,
                            "textAfter": <?= json_encode($block->getData('text_after')) ?>,
                            "designClass": "-<?= $block->getData('design') ?>",
                            "children": {
                                "<?= $block->getData('design') ?>": {
                                    "component": "<?= $block->getDesignComponent() ?>",
                                    "template" : "Amasty_PromoCountdown/design/<?= $block->getData('design') ?>",
                                    "displayArea": "design"
                                }
                            }
                        }
                    }
                }
            }
        }
    </script>
    <?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
        <?php
        $type = 'widget-product-grid';
        $mode = 'grid';
        $image = 'new_products_content_widget_grid';
        $items = $block->getProductCollection()->getItems();
        $showWishlist = true;
        $showCompare = true;
        $showCart = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        $description = false;
        ?>
        <div class="product-flashsale">
            <div class="block widget block-products-list promo-countdown <?= /* @noEscape */ $mode ?> swiper-list widget-swipper-products ">
                <?php if ($block->getTitle()): ?>
                    <div class="block-title">
                        <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
                    </div>
                <?php endif ?>
                <div class="block-content">
                    <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
                    <div class="swiper-container swiper-items products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                        <ol class="product-items <?= /* @noEscape */ $type ?> swiper-wrapper">
                            <?php $iterator = 1; ?>
                            <?php foreach ($items as $_item): ?>
                                <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="product-item swiper-slide">' : '</li><li class="product-item swiper-slide">' ?>
                                <div class="product-item-info">
                                    <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                                        <?= $block->getImage($_item, $image)->toHtml() ?>
                                    </a>
                                    <div class="product-item-details">
                                        <h3 class="product-item-name">
                                            <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                               href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                               class="product-item-link">
                                                <?= $block->escapeHtml($_item->getName()) ?>
                                            </a>
                                        </h3>
                                        <?php if ($templateType): ?>
                                            <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                        <?php endif; ?>

                                        <?= $block->getProductPriceHtml($_item, \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE) ?>

                                        <?php
                                        /** @var \Ecommage\CatalogWidget\Helper\Data $helper */
                                        $helper = $this->helper(\Ecommage\CatalogWidget\Helper\Data::class);//@codingStandardsIgnoreLine?>
                                        <?php if ($helper->displayDiscountPercent($_item)):?>
                                            <span class="percent-discount"><?= /* @noEscape */ $helper->displayDiscountPercent($_item)?></span>
                                        <?php endif;?>
                                        <?= $block->getProductDetailsHtml($_item) ?>

                                        <?php if ($showWishlist || $showCompare || $showCart): ?>
                                            <div class="product-item-inner">
                                                <div class="product-item-actions">
                                                    <?php if ($showCart): ?>
                                                        <div class="actions-primary">
                                                            <?php if ($_item->isSaleable()): ?>
                                                                <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                                <form data-role="tocart-form-<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>" data-product-sku="<?= $block->escapeHtml($_item->getSku()) ?>" data-product-name="<?= $block->escapeHtml($_item->getName()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                                    <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                                    <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                                    <?= $block->getBlockHtml('formkey') ?>
                                                                    <button data-value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>" type="button" id="add-to-cart"
                                                                            title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                            class="action tocart primary">
                                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                    </button>
                                                                </form>
                                                            <?php else: ?>
                                                                <?php if ($_item->isAvailable()): ?>
                                                                    <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                                <?php else: ?>
                                                                    <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                                <?php endif; ?>
                                                            <?php endif; ?>
                                                        </div>
                                                    <?php endif; ?>
                                                    <?php if ($showWishlist || $showCompare): ?>
                                                        <div class="actions-secondary" data-role="add-to-links">
                                                            <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist): ?>
                                                                <a href="#"
                                                                   data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                                    <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                                </a>
                                                            <?php endif; ?>
                                                            <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                                <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);?>
                                                                <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                                    <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                                </a>
                                                            <?php endif; ?>
                                                        </div>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                    <?php if ($block->isMsgVisible($_item)): ?>
                                        <div class="product-item-amount">
                                            <span class="product-amount-content">
                                                <?= $block->escapeHtml(__('Remaining')) ?>
                                                <?= $block->escapeHtml($block->getStockQtyLeft($_item))?>
                                            </span>
                                        </div>
                                    <?php endif ?>
                                </div>
                                <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                            <?php endforeach ?>
                        </ol>
                        <div class="swiper-pagination"></div>
                    </div>
                    <div class="swiper-button-prev"></div>
                    <div class="swiper-button-next"></div>
                    <?= $block->getPagerHtml() ?>
                </div>
            </div>
        </div>
    <?php if($block->getBlockHtml('formkey')): ?>
        <script type="text/x-magento-init">
    {
        ".block.widget [data-role=tocart-form]": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
    </script>
    <?php endif;?>
    <?php endif;?>

</div>
