<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;
/** @var \Ecommage\CatalogWidget\Block\Product\ProductsList $block */

// phpcs:disable Generic.Files.LineLength.TooLong
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
?>
<?php if ($exist = ($block->createCollection() && $block->createCollection()->getSize())): ?>
    <?php
    $type = 'widget-product-grid';
    $mode = 'grid';
    $image = 'new_products_content_widget_grid';
    $items = $block->createCollection();
    $productGifts = [];
    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>
    <div class="block widget block-products-list <?= /* @noEscape */ $mode ?>">
        <?php if ($block->getTitle()): ?>
            <div class="block-title">
                <h2><?= $block->escapeHtml(__($block->getTitle())) ?></h2>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?php if($block->getData('show_gift')):?>
                <?php $productGifts = $block->filterGift($block->createCollection()); ?>
                <?php if($productGifts instanceof Magento\Catalog\Model\ResourceModel\Product\Collection && $productGifts->getSize() > 0):?>
                    <div class="products-gift-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                        <ol class="product-items-gift <?= /* @noEscape */ $type ?>">
                            <?php $iterators = 1; ?>
                            <?php foreach ($productGifts as $productGift): ?>
                                <?= /* @noEscape */ ($iterators++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                                <div class="product-item-info">
                                    <a href="<?= $block->escapeUrl($block->getProductUrl($productGift)) ?>" class="product-item-photo">
                                        <?= $block->getImage($productGift, $image)->toHtml() ?>
                                    </a>
                                    <div class="product-item-details">
                                        <h3 class="product-item-name">
                                            <a title="<?= $block->escapeHtml($productGift->getName()) ?>"
                                               href="<?= $block->escapeUrl($block->getProductUrl($productGift)) ?>"
                                               class="product-item-link">
                                                <?= $block->escapeHtml($productGift->getName()) ?>
                                            </a>
                                        </h3>
                                        <?php if ($templateType): ?>
                                            <?= $block->getReviewsSummaryHtml($productGift, $templateType) ?>
                                        <?php endif; ?>

                                        <?= $block->getProductPriceHtml($productGift, \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE) ?>

                                        <?php
                                        /** @var \Ecommage\CatalogWidget\Helper\Data $helper */
                                        $helper = $this->helper(\Ecommage\CatalogWidget\Helper\Data::class);//@codingStandardsIgnoreLine?>
                                        <?php if ($helper->displayDiscountPercent($productGift)):?>
                                            <span class="percent-discount"><?= /* @noEscape */ $helper->displayDiscountPercent($productGift)?></span>
                                        <?php endif;?>
                                        <?= $block->getProductDetailsHtml($productGift) ?>

                                        <?php if ($showWishlist || $showCompare || $showCart): ?>
                                            <div class="product-item-inner">
                                                <div class="product-item-actions">
                                                    <?php if ($showCart): ?>
                                                        <div class="actions-primary">
                                                            <?php if ($productGift->isSaleable()): ?>
                                                                <?php $postParams = $block->getAddToCartPostParams($productGift); ?>
                                                                <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($productGift->getSku()) ?>" data-product-name="<?= $block->escapeHtml($productGift->getName()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                                    <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                                    <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                                    <?= $block->getBlockHtml('formkey') ?>
                                                                    <button type="submit"
                                                                            title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                            class="action tocart primary">
                                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                    </button>
                                                                </form>
                                                            <?php else: ?>
                                                                <?php if ($productGift->isAvailable()): ?>
                                                                    <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                                <?php else: ?>
                                                                    <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                                <?php endif; ?>
                                                            <?php endif; ?>
                                                        </div>
                                                    <?php endif; ?>
                                                    <?php if ($showWishlist || $showCompare): ?>
                                                        <div class="actions-secondary" data-role="add-to-links">
                                                            <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist): ?>
                                                                <a href="#"
                                                                   data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($productGift) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                                    <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                                </a>
                                                            <?php endif; ?>
                                                            <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                                <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);?>
                                                                <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($productGift) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                                    <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                                </a>
                                                            <?php endif; ?>
                                                        </div>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            <?php $giftModel = $block->getGiftByProduct($productGift); ?>
                                <div class="product-item-info-gift">
                                    <span class="gift-text"><?= $block->escapeHtml(__('Ưu đãi quà tặng'))?></span>
                                    <span class="gift-name"><?= $block->escapeHtml(__('Tặng ngay 1 hộp %1', $giftModel->getName()))?></span>
                                    <span class="gift-image">
                                        <a href="<?= $block->escapeUrl($block->getProductUrl($giftModel)) ?>" class="product-item-photo">
                                            <?= $block->getImage($giftModel, $image)->toHtml() ?>
                                        </a>
                                    </span>
                                </div>
                                <?= ($iterators == count($productGifts) + 1) ? '</li>' : '' ?>
                            <?php endforeach ?>
                        </ol>
                    </div>
                <?php endif;?>
            <?php endif;?>
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <?php if($this->getData('ignore_gift')){$items = $block->ignoreGift($items);}?>
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?> <?= /* @noEscape */ (!$block->getData('show_gift') || $productGifts->getSize() == 0) ? 'no-gift': ''?>">
                <ol class="product-items <?= /* @noEscape */ $type ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                        <div class="product-item-info">
                            <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                            </a>
                            <div class="product-item-details">
                                <h3 class="product-item-name">
                                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                       href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-link">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </h3>
                                <?php if ($templateType): ?>
                                    <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>

                                <?= $block->getProductPriceHtml($_item, \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE) ?>

                                <?php
                                /** @var \Ecommage\CatalogWidget\Helper\Data $helper */
                                $helper = $this->helper(\Ecommage\CatalogWidget\Helper\Data::class);//@codingStandardsIgnoreLine?>
                                <?php if ($helper->displayDiscountPercent($_item)):?>
                                    <span class="percent-discount"><?= /* @noEscape */ $helper->displayDiscountPercent($_item)?></span>
                                <?php endif;?>
                                <?= $block->getProductDetailsHtml($_item) ?>

                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product-item-inner">
                                        <div class="product-item-actions">
                                            <?php if ($showCart): ?>
                                                <div class="actions-primary">
                                                    <?php if ($_item->isSaleable()): ?>
                                                        <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                        <form data-role="tocart-form-<?=  /* @noEscape */  $_item->getId()?>" data-product-sku="<?= $block->escapeHtml($_item->getSku()) ?>" data-product-name="<?= $block->escapeHtml($_item->getName()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                            <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                            <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                            <?= $block->getBlockHtml('formkey') ?>
                                                            <button type="submit"
                                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                    class="action tocart primary">
                                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                            </button>
                                                        </form>
                                                        <script type="text/x-magento-init">
                                                        {
                                                            "[data-role=tocart-form-<?=  /* @noEscape */ $_item->getId()?>], .form.map.checkout": {
                                                                "catalogAddToCart": {
                                                                    "product_sku": "<?= $block->escapeJs($_item->getSku()) ?>"
                                                                }
                                                            }
                                                        }
                                                    </script>
                                                    <?php else: ?>
                                                        <?php if ($_item->isAvailable()): ?>
                                                            <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                        <?php else: ?>
                                                            <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                            <?php if ($showWishlist || $showCompare): ?>
                                                <div class="actions-secondary" data-role="add-to-links">
                                                    <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist): ?>
                                                        <a href="#"
                                                           data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                        <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);?>
                                                        <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
                <?php if ($block->getData('view_all')): ?>
                    <div class="view-all-link">
                        <a href="<?= $block->escapeUrl($block->getCategoryUrl()) ?>"
                           title="<?= $block->escapeHtml(__('View All'))?>"
                           role="button"
                           class="button-link">
                            <?= $block->escapeHtml(__('View All')) ?>
                        </a>
                    </div>
                <?php endif; ?>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
    <?php if($block->getBlockHtml('formkey')): ?>
        <script type="text/x-magento-init">
    {
        ".block.widget [data-role=tocart-form]": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
    </script>
    <?php endif;?>
<?php endif;?>
