<?php
/**
 *  @var $block \Sparsh\MobileNumberLogin\Block\Account\Dashboard\Info
 */
$helper = $this->helper('Ecommage\CustomerFullName\Helper\Data');
?>

<div class="block block-dashboard-info">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Account Information')) ?></strong></div>
    <div class="block-content">
        <div class="box box-information">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Contact Information')) ?></span>
            </strong>
            <div class="box-content">
                <p>
                    <?php if (!empty($helper->isCheckTypeLogin())) :?>
                            <?php $customer = $block->getCustomer(); ?>
                        <?= $block->escapeHtml(sprintf('%s %s',$customer->getLastname(),$customer->getFirstname())) ?><br>
                    <?php else: ?>
                        <?= $block->escapeHtml($block->getName()) ?><br>
                    <?php endif; ?>

                    <?= $block->escapeHtml($block->getCustomer()->getEmail()) ?><?= ($block->getMobileNumber()?'<br>':'');?>
                    <?= $block->escapeHtml($block->getMobileNumber()) ?>
                </p>
                <?= $block->getChildHtml('customer.account.dashboard.info.extra'); ?>
            </div>
            <div class="box-actions">
                <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('customer/account/edit')) ?>">
                    <span><?= $block->escapeHtml(__('Edit')) ?></span>
                </a>
                <a href="<?= $block->escapeUrl($block->getChangePasswordUrl()) ?>" class="action change-password">
                    <?= $block->escapeHtml(__('Change Password')) ?>
                </a>
            </div>
        </div>
        <?php if ($block->isNewsletterEnabled()) : ?>
            <div class="box box-newsletter">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Newsletters')) ?></span>
                </strong>
                <div class="box-content">
                    <p>
                        <?php if ($block->getIsSubscribed()) : ?>
                            <?= $block->escapeHtml(__('You are subscribed to "General Subscription".')) ?>
                        <?php else : ?>
                            <?= $block->escapeHtml(__('You aren\'t subscribed to our newsletter.')) ?>
                        <?php endif; ?>
                    </p>
                </div>
                <div class="box-actions">
                    <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('newsletter/manage')) ?>"><span><?= $block->escapeHtml(__('Edit')) ?></span></a>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
