<?php
use Magento\Framework\App\Action\Action;

/** @var RecentlyViewProduct $block
 * @var \Magento\Framework\Escaper $escaper
 */
$products = $block->createCollection();
if (!count($products)) {
    return;
}
$show_buttons  = explode(',', $block->getData('show_buttons'));
$showAddToCart = in_array('add_to_cart', $show_buttons) ? true : false;
$showWishlist  = in_array('add_to_wishlist', $show_buttons) ? true : false;
$showCompare   = in_array('add_to_compare', $show_buttons) ? true : false;
/** @codingStandardsIgnoreStart */
/** @var Image $_imageHelper */
$_imageHelper   = $this->helper('Magento\Catalog\Helper\Image');
$postDataHelper  = $this->helper('Ecommage\CustomCatalog\Helper\PostHelper');
$compareHelper  = $this->helper('Magento\Catalog\Helper\Product\Compare');
$wishlistHelper = $this->helper('Magento\Wishlist\Helper\Data');
$arr = $postDataHelper->getTitleAddToCart($postDataHelper->getViewModelProduct()->generateJsonConfig($products->getItems()));
/** @codingStandardsIgnoreEnd */

use Magento\Catalog\Helper\Image;
use NiceForNow\RecentlyProduct\Block\RecentlyViewProduct;

?>

<hr>
<div class="recently-view-product-slider swiper-custom product-list-custom">
    <div class="content-heading">
        <h2 class="title text-center-xs"><strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong></h2>
    </div>
    <div class="swiper-container" id="swiper_container_recently_view_products">
        <div class="swiper-wrapper">
            <?php foreach ($products as $product) : ?>
                <?php $title = $postDataHelper->getButtonAddToCart($product,$arr);?>
                <div class="swiper-slide">
                    <?php
                    $productImage = $_imageHelper->init($product, 'category_page_list')->constrainOnly(false)->keepAspectRatio(true)->keepFrame(false)->resize(400)->getUrl();
                    $productUrl   = $product->getUrlModel()->getUrl($product);
                    ?>
                    <div class="item product product-item <?= !empty($title) ? 'ampreorder-observed' :'' ?>">
                        <div data-container="product-grid" class="product-item-info">
                            <a tabindex="-1" class="product photo product-item-photo" href="<?= /* @noEscape */
                            $productUrl; ?>">
                                <span class="product-image-container">
                                    <span style="padding-bottom: 100%;" class="product-image-wrapper">
                                        <img
                                             alt="<?= /* @noEscape */
                                             $product->getName(); ?>"
                                             src="<?= /* @noEscape */
                                             $productImage; ?>"
                                             class="product-image-photo"
                                        />
                                    </span>
                                </span>
                            </a>
                            <div class="product details product-item-details">
                                <strong class="product name product-item-name">
                                    <a href="<?= /* @noEscape */
                                    $productUrl; ?>" class="product-item-link">
                                        <?= /* @noEscape */
                                        $product->getName(); ?>
                                    </a>
                                </strong>
                                <?= /* @noEscape */
                                $block->getProductPrice($product); ?>
                                <!-- <span class="percent-discount">-20%</span> -->
                                <?php
                                /** @var \Ecommage\CatalogWidget\Helper\Data $helperEcom */
                                $helperEcom = $this->helper(\Ecommage\CatalogWidget\Helper\Data::class);//@codingStandardsIgnoreLine?>
                                <?php if ($helperEcom->displayDiscountPercent($product)):?>
                                    <span class="percent-discount"><?= /* @noEscape */ $helperEcom->displayDiscountPercent($product)?></span>
                                <?php endif;?>
                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions">
                                        <?php if ($showAddToCart) : ?>
                                            <div class="actions-primary">
                                                <?php if ($product->isSaleable()): ?>
                                                        <?php $postParams = json_decode($postDataHelper->getPostData($block->getAddToCartUrl($product), ['product' => $product->getEntityId()]));?>
                                                    <form data-role="tocart-form-<?= $block->escapeHtmlAttr($product->getEntityId()) ?>" data-product-sku="<?= $block->escapeHtml($product->getSku()) ?>" id="product_add_tocart_form<?= $escaper->escapeHtmlAttr($product->getId()) ?>" data-product-name="<?= $block->escapeHtml($product->getName()) ?>" action="<?= $block->escapeUrl($postParams->action) ?>" method="post">
                                                        <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams->data->product) ?>">
                                                        <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams->data->uenc ?>">
                                                        <?= $block->getBlockHtml('formkey') ?>
                                                        <button data-value="<?= $block->escapeHtmlAttr($product->getEntityId()) ?>" type="button" id="add-to-cart"
                                                                title="<?= $block->escapeHtml(__(!empty($title) ? $title : 'Add to Cart')) ?>"
                                                                class="action tocart primary">
                                                            <span><?= $block->escapeHtml(__(!empty($title) ? $title : 'Add to Cart')) ?></span>
                                                        </button>
                                                    </form>
                                                <?php else: ?>
                                                    <?php if ($product->getIsSalable()): ?>
                                                        <div class="stock available"><span><?= /* @noEscape */
                                                                __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?= /* @noEscape */
                                                                __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>

                                        <div class="actions-secondary" data-role="add-to-links">
                                            <?php if ($showWishlist || $showCompare): ?>
                                                <div class="secondary-addto-links actions-secondary"
                                                     data-role="add-to-links">

                                                    <?php if ($wishlistHelper->isAllow() && $showWishlist): ?>
                                                        <a href="#" data-post='<?= /* @noEscape */
                                                        $block->getAddToWishlistParams($product); ?>'
                                                           class="action towishlist" data-action="add-to-wishlist"
                                                           title="<?= /* @noEscape */
                                                           __('Add to Wish List') ?>">
                                                            <span><?= /* @noEscape */
                                                                __('Add to Wish List') ?></span>
                                                        </a>
                                                    <?php endif; ?>

                                                    <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                        <a href="#" class="action tocompare"
                                                           data-post='<?= /* @noEscape */
                                                           $compareHelper->getPostDataParams($product); ?>'
                                                           data-role="add-to-links"
                                                           title="<?= /* @noEscape */
                                                           __('Add to Compare'); ?>">
                                                            <span><?= /* @noEscape */
                                                                __('Add to Compare') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <!-- Add Arrows -->
    <div class="swiper-button-next-recently swiper-action swiper-button-next"></div>
    <div class="swiper-button-prev-recently swiper-action swiper-button-prev"></div>
</div>
<script>
    require(['jquery', 'swiper'], function ($, Swiper) {
        jQuery(document).ready(function () {
            var swiper = new Swiper('#swiper_container_recently_view_products', {
                slidesPerView: 5,
                spaceBetween: 20,
                autoplay: {
                    delay: 5000,
                    disableOnInteraction: true,
                },
                pagination: {
                    clickable: true,
                },
                navigation: {
                    nextEl: '.swiper-button-next-recently',
                    prevEl: '.swiper-button-prev-recently',
                },
                breakpoints: {
                    0: {
                        slidesPerView: '1.5',
                        spaceBetween: 10
                    },
                    374: {
                        slidesPerView: '2.37',
                        spaceBetween: 10
                    },
                    768: {
                        slidesPerView: '3.4',
                        spaceBetween: 20
                    },
                    1024: {
                        slidesPerView: 5,
                        spaceBetween: 20
                    }
                }
            });
        });
    });
</script>
<script type="text/x-magento-init">
{
    "[data-role=tocart-form], .form.map.checkout": {
        "catalogAddToCart": {
            "product_sku": "<?= $escaper->escapeJs($product->getSku()) ?>"
        }
    }
}
</script>
